### ISSUE TITLE
DTLS peer certificates

### ISSUE THREAD

**Issue by jdbruijn** [plgd-dev/go-coap#134]
I noted that in v2.0.2 I can't get the peer certificates any more, which were added in #115. Am I just looking in the wrong place (`responseWriter.Client()`) or was that code removed somewhere in v2.0.1 ?

**Comment by jkralik** [comment]
Yeah Sorry I want to add option to get underlying connection + setter for set a value to the context. And then you can store there parsed peer certificate,

**Comment by cristovao-trevisan** [comment]
@jdbruijn , you can now access the peer certificates (using the master at least).
Check the example at https://github.com/plgd-dev/go-coap/tree/master/examples/dtls/pki

This issue can probably be closed now

**Comment by jdbruijn** [comment]
@cristovao-trevisan Thanks for the great work on this! Will give it a try sometime!
