### ISSUE TITLE
How can I send a NonConfirmable message?

### ISSUE THREAD

**Issue by d1ee** [plgd-dev/go-coap#150]
I saw at the code, and find out that the udp part of `clientConn.Do` and `clientConn.WriteMessage` eventually does this: `req.SetType(udpMessage.Confirmable)`.

What is the reason of doing this? And how can I send a `NonConfirmable` message, which isn't manipulated by the sender?

**Comment by jkralik** [comment]
Yes this is not supported for now. For blockwise transfer we always send confirmable message via WriteMessage.
To fix issue:
 - we can always create confirmable message and via settype you can change it.
- create WriteRawMessage where user is responsible for all sets.

**Comment by d1ee** [comment]
@jkralik Thanks for your response.
