### ISSUE TITLE
How to check if a message is confirmable?

### ISSUE THREAD

**Issue by Niondir** [plgd-dev/go-coap#155]
I'm setting up a CoAP UDP Server. The Handler interface does not provide the message Type.

How to get the UDP Message?

**Comment by jkralik** [comment]
It depends what you register as Handler. If it is [mux](https://github.com/plgd-dev/go-coap/tree/master/mux) then it doesn't provide you such information. If you need handle ACK message you need to use `WithHandlerFunc` server option, where you get  udp request with Type. After that you can use mux similar as this [code](https://github.com/plgd-dev/go-coap/blob/9bdc8a6450d15cd09e36d863abb7b7a766c2099d/udp/client/mux.go#L14 ).

**Comment by Niondir** [comment]
Okay thanks, so I can hook into handlerFuncToMux to handle deduplication and sending ACKs I guess. I will try that out.
