### ISSUE TITLE
Are ACKs for Confirmable requests and message deduplication handled by this library?

### ISSUE THREAD

**Issue by Niondir** [plgd-dev/go-coap#156]
Hi,
I cant find any information about this.

I know the old version of this library did not automatically sent ACK responses. Also request deduplications based on messageIDs for retries had to be done in the app. Is this still required?

**Comment by jkralik** [comment]
Deduplications is missing for now.  If you have time I will glad accept a contribution (it needs to be involved in https://github.com/plgd-dev/go-coap/blob/9bdc8a6450d15cd09e36d863abb7b7a766c2099d/udp/client/clientconn.go#L464).

**Comment by Niondir** [comment]
Okay that's fine.

When I get some code based on the UDP Handler func as suggested in #155 I will share it. Either one can just opt in for dedpulication and ACk handling or we can later pull it into the stack.

**Comment by jkralik** [comment]
I think it needs to be in stack because we want to deduplicate messages before any handler is called. Eg (blockwise transfer)

**Comment by Niondir** [comment]
This is my solution. I still need some testing. Deduplication is handled before routing:

{code}
func handlerFuncToMux(m mux.Handler) coapUdp.HandlerFunc {
	h := func(w *coapUdpClient.ResponseWriter, r *coapUdpPool.Message) {

		// TODO: Handle ACK and deduplication here?
		if handleDuplicateMessage(w, r) {
			return
		}

		muxw := &muxResponseWriter{
			w: w,
		}
		muxr, err := coapUdpPool.ConvertTo(r)
		if err != nil {
			return
		}
		m.ServeCOAP(muxw, &mux.Message{
			Message:        muxr,
			SequenceNumber: r.Sequence(),
		})
	}
	return h
}


// Important to lock with mutex! Else we rise server panics
var msgIdCache = map[net.Addr]uint16{}
var msgIdCacheMutex = sync.Mutex{}

// handleDuplicateMessage returns true when the message is a duplicate and should not be handled
func handleDuplicateMessage(w *coapUdpClient.ResponseWriter, r *coapUdpPool.Message) bool {
	if r.Message == nil {
		return false
	}

	msgIdCacheMutex.Lock()
	defer msgIdCacheMutex.Unlock()

	lastHandledMsgId, ok := msgIdCache[w.ClientConn().RemoteAddr()]

	if ok && r.MessageID() == lastHandledMsgId {
		if r.Type() == udpMsg.Confirmable {
			logrus.WithField("msgId", lastHandledMsgId).Infof("Already handled message id - send confirm")
			_ = w.SetResponse(codes.Empty, msg.TextPlain, nil)
			return true
		}
		logrus.WithField("msgId", lastHandledMsgId).Infof("Already handled message id")
		return true
	}
	msgIdCache[w.ClientConn().RemoteAddr()] = r.MessageID()
	return false
}
{code}

**Comment by jkralik** [comment]
Nice. But:
- when do you remove entry  from `msgIdCache`?
- why only confirmable messages?
- why only one entry ?
- what about multicast ? - same request can comes from multiple interfaces.

To store more messages you can use `github.com/patrickmn/go-cache` where you can set expiration time.

**Comment by Niondir** [comment]
Well, we came to the point that it does not work this way. Main reason is, that the handler is only called after all blocks of a blockwise transfer is completed.

The unsupported deduplication currently also leads to a bug where a new request is created when the last block is lost and thus the re-transmission of the client is handled with an error response.

**Comment by Niondir** [comment]
I'm working in this issue. Currently the second request with the same msgId does not return when loaded from cache.
It seems not trivial to just skip the handler.
What's also breaks the request is to unmarshal the cached response directly into w.response.

Maybe someone already has some tips what to watch out for, I can post more details when at home again.

**Comment by Niondir** [comment]
I was sending 2 requests with the same MessageID but different tokens. So not getting a response for the second request is legit, when deduplication is only based on the MessageID (as described in RFC 7252). 

With the submitted PR, the deduplication seems to work as expected.
