### ISSUE TITLE
ResponseWriter.SetResponse does not work with empty reader

### ISSUE THREAD

**Issue by Niondir** [plgd-dev/go-coap#157]
This does lead to an EOF

    w.SetResponse(codes.Created, msg.AppCBOR, bytes.NewReader([]byte{}))

To produce an empty payload one has to call

    w.SetResponse(codes.Created, msg.AppCBOR, nil)

either the first case should just work, or the usage should be documented on the `SetResponse` method.

**Comment by jkralik** [comment]
Yes this is a bug.
