### ISSUE TITLE
howto get data from resp.Body()

### ISSUE THREAD

**Issue by IHIDCHAOS** [plgd-dev/go-coap#158]
Hi, I am using this package for my coap project, but there are some problems.
When I send a "login" message to the coap cloud server, the server will return some data. I need to use these data (called server token) as the coap token for subsequent interactions with the server, which requires req.SetToken(). But I don't have a good way to get this token, can you give me some help? Thank you!
The data in the picture below is what I really need.
![image](https://user-images.githubusercontent.com/20263334/91389061-24840d00-e86b-11ea-8b7d-8e4a12c1efa7.png)

**Comment by jkralik** [comment]
Hi. 
Sure you just need to call `ioutil.ReadAll(resp.Body)`:
```go
import "github.com/plgd-dev/go-coap/v2/udp/message/pool"
... 
token, err := ioutil.ReadAll(resp.Body)
if err != nil {
  panic(err)
}
if len(token) == 0 || len(token) > 8 {
  panic(err)
}
req := pool.AcquireMessage(ctx)
req.SetToken(token)
req.SetCode(codes.GET)
...
resp, err := cc.Do(req)
if err != nil {
   panic(err)
}

```

**Comment by IHIDCHAOS** [comment]
I modified it according to your reply and the result is correct. Thank you very much!
