### ISSUE TITLE
go-coap/message/codes/codes.go got wrong package route

### ISSUE THREAD

**Issue by Kracker1911** [plgd-dev/go-coap#159]
I use Goland to test the demo in README.md.
When compiling it shows the error: "github.com/plgd-dev/go-coap/message/codes expects imports github.com/plgd-dev/go-coap/codes" .
Deleted the comment "//imports github.com/plgd-dev/go-coap/codes" in codes.go, demo compiles normal.

**Comment by jkralik** [comment]
Thx for report a issue. I removed stale comment from the package. https://github.com/plgd-dev/go-coap/commit/067a87acf934df243135ceaf9ae97aa9338745f0

**Comment by Danielius1922** [comment]
@jkralik I think we can close this, right?
