### ISSUE TITLE
Help using options on client requests

### ISSUE THREAD

**Issue by bocajim** [plgd-dev/go-coap#162]
Hello,

My pattern is that I have a CoAP server that is receiving requests, and it then uses w.Client() to get access to the client to set an observation back in the remote server.  I am trying to set an option (for example the Accept option to set that I want the observation notifications to be sent in Lwm2mTlv encoding, but I cant find an example of how to use the options on the w.Client().Observe() function.

For general GET requests, I am doing something like this:

	req, _ := client.NewGetRequest(ctx, "3/0")
        req.SetAccept(message.AppLwm2mTLV)
	rsp, err := w.Client().Do(req)

Any help is appreciated.

**Comment by jkralik** [comment]
Hi.
Here is a sample with options.
```go
opts := make(message.Options, 0, 1)
buf := make([]byte, 4)
opts, _, _ = opts.SetAccept(buf, message.AppLwm2mTLV)
err := client.Observe(ctx, "3/0", func(notification *message.Message){...}, opts...)
```

**Comment by bocajim** [comment]
Thanks, that will work.  Maybe in the future it would help to have a helper that builds the options so its not so laborious.
