### ISSUE TITLE
Dynamically register routes

### ISSUE THREAD

**Issue by beriberikix** [plgd-dev/go-coap#171]
I'd like to start a discussion about supporting the ability to dynamically register routes. This is a common use case for an API server where routing information may kept in an external store (like a DB) and another application is adding and removing routes without having to restart the API server. We have a current prototype in a private fork (designed by @andrewhoff) that does with a modified `mux` and custom routing table logic. Would there be interest in adding support for something like this in `go-coap`?

**Comment by jkralik** [comment]
Sure. This could be very helpful 👍

**Comment by jkralik** [comment]
Closing for not respond
