### ISSUE TITLE
Client connection does not close net connection 

### ISSUE THREAD

**Issue by cheremuk** [plgd-dev/go-coap#172]
Dial creates a client connection to the given target **conn**. This connection is passed to a new session.
```

// Dial creates a client connection to the given target.
func Dial(target string, opts ...DialOption) (*ClientConn, error) {
	cfg := defaultDialOptions
	for _, o := range opts {
		o.applyDial(&cfg)
	}

	var conn net.Conn
	var err error
	if cfg.tlsCfg != nil {
		conn, err = tls.DialWithDialer(cfg.dialer, cfg.net, target, cfg.tlsCfg)
	} else {
		conn, err = cfg.dialer.DialContext(cfg.ctx, cfg.net, target)
	}
	if err != nil {
		return nil, err
	}
	return Client(conn, opts...), nil
}
```

Closing **ClientConn** will cancel underlying session which will leak the underlying net connection: this socket won't be closed. 

The fix could be to add on close function to close this socket upon closing client **ClientConn**. Of course, this should be invoked only if customers didn't pass their own connection.

**Comment by jkralik** [comment]
Hi @cheremuk .

Thx for reporting and analyzing the bug. I created fix and it introduce option `WithCloseSocket` which user can add via call `Client`. For `Dial` it is automatically added.

Pls could you check if the fix solve the issue with the branch `fixCloseSocket`?
