### ISSUE TITLE
Connection stays open when disabling keep-alive

### ISSUE THREAD

**Issue by jdbruijn** [plgd-dev/go-coap#178]
I think the connections might stay open indefinitely in the DTLS listener when using it with `dtls.WithKeepAlive(nil)`. I expect that when disabling keep-alive, we at least would still see the CPU usage and number of goroutines drop back to zero/original after the context duration is expired or something, but after an hour it is still steady high.

We ran into a problem where our server, using `go-coap`, stays on a high CPU usage after clients have finished there connections. At that point there have been e.g. 500 connections, of which the clients are all finished now and don't sent any more messages, and no new incoming connections. I've been trying to debug the issue and found that when I remove `dtls.WithKeepAlive(nil)` from the DTLS server configuration `dtls.NewServer`, so enable keep-alive, the CPU drops back to zero as expected.

I've also seen that the goroutines count stays high and stable when disabling keep-alive and drop back to the original value with keep-alive enabled.

@jkralik Do you have any ideas whether this is indeed the case or maybe something else is going on? I'm looking into this further myself as well, but I'm not as familiar with the code of course.

**Comment by jkralik** [comment]
Hi @jdbruijn 

I have two points:

- UDP/DTLS doesn't have internal keepalive  feature as tcp connection. So if you set `dtls.WithKeepAlive(nil)` you need to manage inactive connection by your application -> It means you need decide when the connection need to be closed.(eg retrieve some path of the client every x seconds and if it is fails, close the connection.). We can modify `https://github.com/plgd-dev/go-coap/blob/master/net/keepalive/keepalive.go` to allow set ping function instead of have it in interface.

- try increase hearbeat to 20 seconds via `dtls.WithHeartBeat(time.Duration)` . The parameter defines wake up from operations `accept, read, write`  -> so in worst case terminate server takes 20 seconds because it waits for close all connections. By default it is 100ms.

**Comment by jdbruijn** [comment]
Thanks for your quick reply. I've changed this to a question rather than a bug, based on your comment.

I understand it is very difficult to determine whether a connection is finished and may be closed. I agree the keep-alive mechanism you've implemented would be the way to go. The client side doesn't support that at the moment unfortunately so I do need to disable the keep-alive for now.

> We can modify `https://github.com/plgd-dev/go-coap/blob/master/net/keepalive/keepalive.go` to allow set ping function instead of have it in interface.

This won't work for me at the moment because the problem with the client is that it would receive an incoming message that isn't the message it has been waiting for and after that doesn't listen for another message. This has to do with the client implementation unfortunately.

> try increase hearbeat to 20 seconds

I've tried increasing the heartbeat but it didn't make much difference in my case.

I thought of another option, which is also what NGINX uses for DTLS. I'm adding a timer to the connection/session and resetting the timer each time I receive a message. When I don't receive a message for a given time, the timer will timeout and close the connection. NGINX with DTLS does the same but for both incoming and outgoing messages and have the timeout configured to 10 minutes.

I can imagine this is a very specific approach and has some strong assumptions, but I think it is the best I'll get without the keep-alive mechanism. The patch I've come up with that is shown below. I don't know whether this is the best way to implement it, probably not, could you please give feedback on that? If it is something you see being helpful to others and appropriate to be implemented I'd be happy to send a PR for it, then configurable with `dtls.WithTimeout` or something like that.

<details><summary>Timeout patch</summary>

```patch
diff --git a/dtls/session.go b/dtls/session.go
index 340f289..5634514 100644
--- a/dtls/session.go
+++ b/dtls/session.go
@@ -6,6 +6,7 @@ import (
        "net"
        "sync"
        "sync/atomic"
+       "time"

        coapNet "github.com/plgd-dev/go-coap/v2/net"
        "github.com/plgd-dev/go-coap/v2/udp/client"
@@ -117,9 +118,32 @@ func (s *Session) Run(cc *client.ClientConn) (err error) {
                }
        }()
        m := make([]byte, s.maxMessageSize)
+
+       timeout := time.Second * 10
+       timer := time.NewTimer(timeout)
+       t := time.Now()
+       fmt.Printf("%v: Started timer\n", t.String())
+       defer timer.Stop()
+
+       go func() {
+               for {
+                       select {
+                       case <-timer.C:
+                               t := time.Now()
+                               fmt.Printf("%v: Closing connection (timeout)\n", t.String())
+                               cc.Close()
+                               return
+                       }
+               }
+       }()
+
        for {
                readBuf := m
                readLen, err := s.connection.ReadWithContext(s.Context(), readBuf)
+               t := time.Now()
+               fmt.Printf("%v: Resetting timeout\n", t.String())
+               timer.Reset(timeout)
+
                if err != nil {
                        return err
                }
```

</details>

**Comment by jkralik** [comment]
@jdbruijn OK I understand. So we can create option `WithInactivityMonitor (interval time.Deration, func onInactive(cc *client.ClientConn))` to all protocols and user can decide what happend in `func onInactive` eg - close connection.

**Comment by Niondir** [comment]
After reading this, I might have the same problem on my server - even though I never monitored it. But we also do no use the KeepAlive feature.

I like the idea with the `WithInactivityMonitor` I would even suggest a default timeout for all UDP connections. e.g. 10 minutes and a default action that closes the connection.

**Comment by Niondir** [comment]
`Session.Run()` only affects clients. I provided a PR that should fix the issue for UDP. For DTLS one must copy the concept or make the solution a bit more generic and move it to a separate package. Whatever is preferred?

**Comment by jdbruijn** [comment]
Apologies for the long inactivity from my side. Wonderful to see it is implemented now, thanks so much for the work to both of you.
