### ISSUE TITLE
Notifications stop being received silently when the sequence number rolls over

### ISSUE THREAD

**Issue by bocajim** [plgd-dev/go-coap#179]
Hello,

I have an issue where I have long lived observations between client and server.  After some time, the server rolls over its sequence number, and after that no notifications are received by my application anymore.  I found the issue is here:

(clientobserve.go line 70ish
`if obsSequence != 0 && o.obsSequence > obsSequence {
		return false
	}`

After the false return, there is no error or notification to the client that notifications have been discarded and an observe needs to be re-issued.  

Reading https://tools.ietf.org/html/rfc7641#section-4.4, I can't tell if the implication is that the maximum lifetime of an observation is intended to be 256 seconds, but it seems like there needs to be some way to detect a rollover and reset the sequence without requiring a new observation to be sent...

**Comment by jkralik** [comment]
Thx for reporting a bug. I will fix it at the end of next week. Great job !
