### ISSUE TITLE
Anyone opposed to a methos to adjust the retransmit timers and counters on a connection

### ISSUE THREAD

**Issue by bocajim** [plgd-dev/go-coap#180]
Hello,

I have an IoT use case where the server is in the cloud, devices connect and I extract the client connection to talk back to the device.  I need to be able to tweak the retransmit timers and counters on that connection (based on data stored in my server).  Currently the values in the ClientConn are private, so I would like to expose them with a simple method...

Any objections?  I can create a pull request...

**Comment by jkralik** [comment]
Sure. Please create PR .

**Comment by Niondir** [comment]
Is PR #193 what you need?

Note that each client gets a new connection with the default parameters from the server. 
For the same remote endpoint (IP+Port) the same ClientConn is reused afterwards.
