### ISSUE TITLE
how to suppress "context canceled" message

### ISSUE THREAD

**Issue by slaesh** [plgd-dev/go-coap#182]
I am using this method to post something to my coap-network:

```golang

// Post ...
func Post(ip config.IPv6, payload string) {
	co, err := udp.Dial("[" + string(ip) + "]:5683")
	if err != nil {
		log.Fatalf("Error dialing: %v", err)
	}
	defer co.Close()

	// create context with timeout
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	// send our post
	resp, err := co.Post(ctx, "set/output", message.AppJSON, strings.NewReader(payload))
	if err != nil {
		fmt.Printf("Error sending post: %v\n", err)
		return
	}

	// read "data" from the ACK response
	if resp.Type() == udpMessage.Acknowledgement {
		data, _ := ioutil.ReadAll(resp.Body())
		fmt.Println("ACK:", string(data))
	}

	// do we need to send an ACK?
	if resp.Type() == udpMessage.Confirmable {
		fmt.Println("send ACK")

		resp.Message.Reset()                     // dont sent content again
		resp.SetType(udpMessage.Acknowledgement) // its an ACK..

		err = co.WriteMessage(resp)
		if err != nil {
			fmt.Println("something went wrong..")
		}
	}

	fmt.Println("post done!")
}
```

Works fine! Thanks for that! ;) But what is a bit annoying.. I am getting all the time this message after a transmission:

![image](https://user-images.githubusercontent.com/55546823/99773894-612f6f80-2b0d-11eb-9d73-ad22b6829d90.png)

How can I suppress this "context canceled" message?

Seems like it comes from here:

![image](https://user-images.githubusercontent.com/55546823/99773837-4b21af00-2b0d-11eb-86ae-5689e415ae84.png)

Am I doing something wrong?

**Comment by jkralik** [comment]
Hi Slaesh. Could send me a backtrace where the error was created ? With `udp.WithErrors` you can suppress it - just set the option in Dial. `udp.Dial(..., udp.WithErrors(func (err error) {}))`

**Comment by slaesh** [comment]
Thanks for your message. Will try that tomorrow!

How would I generate the backtrace?

**Comment by slaesh** [comment]
`udp.WithErrors(func (err error) {})` works. feels kinda like wrong.. I mean there was no error? cancel was called during the defer thing .. or?

**Comment by Niondir** [comment]
I guess the error comes from:

`func (c *UDPConn) ReadWithContext()`

	select {
	case <-ctx.Done():
		return -1, nil, ctx.Err()
	default:
	}

And is bubbled up till `client.go`

	go func() {
		err := cc.Run()
		if err != nil {
			cfg.errors(err)
		}
	}()

I can't find why it's printed to log in your case.
