### ISSUE TITLE
How to get the PSK client's hint in an incoming request/middleware

### ISSUE THREAD

**Issue by alvarowolfx** [plgd-dev/go-coap#196]
Hey folks, 

I'm trying to identify the CoAP client later during an incoming request by checking their DTLS identification. I saw that there is an example on the repo to do that using [DTLS + PKI](https://github.com/plgd-dev/go-coap/blob/master/examples/dtls/pki/server/main.go), where we register a `onNewClientConn` method and we can put the client certificate on the request context. 

I'm trying do to kind of the same thing but with DTLS + PSK, so I need to access the Client's Hint on the incoming handler, because right now seems like the only place that I can access the PSK Client Hint is on the PSKCallback when configuring the DTLS Server. So what I'm trying to do would be more or less like this:

```
func handleA(w mux.ResponseWriter, r *mux.Message) {
	clientHint := r.Context.Value("client-hint").([]byte)
	log.Println("Client's Hint:", string(clientHint))

	log.Printf("got message in handleA:  %+v from %v\n", r, w.Client().RemoteAddr())
	err := w.SetResponse(codes.GET, message.TextPlain, bytes.NewReader([]byte("A hello world")))
	if err != nil {
		log.Printf("cannot set response: %v", err)
	}
}

func onNewClientConn(cc *client.ClientConn, dtlsConn *piondtls.Conn) {
	clientHint := dtlsConn.ClientHint() // <-- Missing part, How to get the client PSK hint here ?
	cc.SetContextValue("client-hint", clientHint)
	cc.AddOnClose(func() {
		log.Println("closed connection")
	})
}

dtlsConfig := &piondtls.Config{
	PSK: func(hint []byte) ([]byte, error) {
                // This seems to be the only place available to get the PSK Client Hint 
		g.logger.Infof("Client's identifier: %s", hint)
		ctx := context.Background()
		identity := string(hint)
		psk, err := g.deviceAuthService.GetKeyByTypeIdentity(ctx, identity, credentials.CredentialTypes.PreSharedKey)
		if err != nil {
			g.logger.Errorf("identifier lookup err: %v", err)
			return nil, err
		}
		return []byte(psk), nil
	},
	CipherSuites: []piondtls.CipherSuiteID{
		piondtls.TLS_PSK_WITH_AES_128_GCM_SHA256,
		piondtls.TLS_PSK_WITH_AES_128_CCM_8,
		piondtls.TLS_PSK_WITH_AES_128_CCM,
	},
}
```

But by checking the project repo, I could not figure out a way to expose a `ClientHint` method on ClientConn or DTLSConn, so I'm creating this issue to see if I can get some guidance. 

Thanks in advance and will be happy to collaborate if needed to make this work ( if it makes sense of course )

**Comment by jkralik** [comment]
I want to suggest to contribute the feature to the pion/dtls and extend `ConnectionState` about member `PeerHint []byte` or something similar.

**Comment by alvarowolfx** [comment]
Thanks for the suggestion @jkralik. I created a PR on pion/dtls to add a `IdentityHint` field to the State struct. If you don't mind, would be awesome if you take a quick look on the PR to see if that is the correct way of doing. 

https://github.com/pion/dtls/pull/335

**Comment by alvarowolfx** [comment]
Gonna close this issue because this was solved with the https://github.com/pion/dtls/pull/335. Thanks for the help @jkralik.
