### ISSUE TITLE
crash when no payload package is received

### ISSUE THREAD

**Issue by okwendell** [plgd-dev/go-coap#206]
<img width="1435" alt="crash" src="https://user-images.githubusercontent.com/24885897/106868014-3797e480-6709-11eb-9711-19d6776bb240.png">

**Comment by okwendell** [comment]
Crash occurred while block-wish was receiving data

**Comment by jkralik** [comment]
@okwendell  Could you test it with branch f`ixSegBWT` if it solve the issue ?

**Comment by okwendell** [comment]
ok

**Comment by okwendell** [comment]
It's working fine now. thx.
