### ISSUE TITLE
goroutine leak

### ISSUE THREAD

**Issue by okwendell** [plgd-dev/go-coap#222]
hi:

After I stop sending COAP requests, goroutine not less, The UDP connection is not broken....

code: github.com/plgd-dev/go-coap/v2 v2.3.1-0.20210205144109-407dab98cdeb

![image](https://user-images.githubusercontent.com/24885897/115109785-61437680-9faa-11eb-9a1a-e75931b0770e.png)

**Comment by okwendell** [comment]
![image](https://user-images.githubusercontent.com/24885897/115232176-01cf9d00-a149-11eb-93c7-477062ee1e94.png)

The parameters(key） will change in func AddOnClose...

**Comment by jkralik** [comment]
Hi @okwendell 
This `key` is used for identify connection and it is remote address. I check it and it correct. The leaked go-routine will be destroyed by GC when after connection/listener was destroyed. Each connection has own cache so if you have 20 connections then 20 goroutines will be there.
I want to remove the cache in near future (~2 months)

**Comment by okwendell** [comment]
hi @jkralik 
I did not enable KeepAlive, My COAP server has been receiving attack packets, then created a connection after receive an new addr packet.these connections were not managed by me, resulting in a leak.
