### ISSUE TITLE
Incorrect NSTART handling

### ISSUE THREAD

**Issue by kegsay** [plgd-dev/go-coap#226]
I've been wondering why NSTART is a `time.Duration` when, as far as I understand, it is the max number of simultaneous outstanding requests to the client/server. Looking at the [use of nstart](https://github.com/plgd-dev/go-coap/blob/4d466801917705aec7cd97b6b53c7502d4c1f7c5/udp/client/clientconn.go#L246) I don't see how this follows the RFC:

```
   In order not to cause congestion, clients (including proxies) MUST
   strictly limit the number of simultaneous outstanding interactions
   that they maintain to a given server (including proxies) to NSTART.
   An outstanding interaction is either a CON for which an ACK has not
   yet been received but is still expected (message layer) or a request
   for which neither a response nor an Acknowledgment message has yet
   been received but is still expected (which may both occur at the same
   time, counting as one outstanding interaction).  The default value of
   NSTART for this specification is 1.
```
https://datatracker.ietf.org/doc/html/rfc7252#section-4.7

Am I missing something here? Thanks!

**Comment by jkralik** [comment]
Thx for reporting - this a bug.
