### ISSUE TITLE
missing coap messages

### ISSUE THREAD

**Issue by slaesh** [plgd-dev/go-coap#227]
currently struggling with some missing messages which I cant "handle" in my middleware somehow..
but the messages are sent, I can see them via wireshark... and there is a c++ implementation which is working fine, what I am currently trying to port to golang! =)

scenario:

end-device: fdde:ad00:beef:0:c61c:db97:a036:c51a
server: fdde:ad00:beef:0:cd56:da33:3bf5:6a1b

1. end-device sends a broadcast registration message "oad/reg"
2. server sends ack
3. server sends msg to end-device directly "oad/ntf"
4. end-device sends ack
5. end-device starts sending requests DIRECTLY to the server "oad/img" <--- those are "missing"
6. server "cant see those messages"..
7. end-device tries to re-transmit several times

and then there are those "destination unreachable" messages, have no clue where are they from.

see the wireshark capture and a screenshot attached.

[wireshark_coap_failure_export.pcapng.tar.gz](https://github.com/plgd-dev/go-coap/files/6464532/wireshark_coap_failure_export.pcapng.tar.gz)

![wireshark_coap_failure_Screenshot_2021-05-12_08-42-57](https://user-images.githubusercontent.com/55546823/117940532-71304b00-b309-11eb-9019-801922e70d6a.png)

server init

```golang

// InitCoapServer ...
func InitCoapServer(port int32, mwf ...mux.MiddlewareFunc) {
	coapRouter.Use(mwf...)

	ipv6AddrStr := fmt.Sprintf(":%d", port)
	udpListener, err := COAPNET.NewListenUDP("udp6", ipv6AddrStr)
	if err != nil {
		log.Println(err)
		return
	}

	defer udpListener.Close()

        // do we need that? seems like it makes no difference..
	//err = udpListener.SetMulticastLoopback(true)
	//if err != nil {
	//	panic(err)
	//}

	s := udp.NewServer(
		udp.WithMux(coapRouter),
		udp.WithKeepAlive(nil), // important for sleepy end devices
	)

	defer s.Stop()

	fmt.Println("start coap server..")
	fmt.Println(udpListener.Network(), udpListener.LocalAddr(), udpListener.RemoteAddr())

	log.Fatal(
		s.Serve(udpListener),
	)
}

```

The starting logs looking like this:

coap          | start coap server..
coap          | udp6 [::]:5683 <nil>

to my setup:

I am using wpantund, which is creating a ethernet-interface and is using a OpenThread border-router to bridge all COAP messages into this interface.
Which is working fine, but somehow those "direct" messages aren't handled somehow..

ip link show of  the created interface, called "wpan0"

![ip_link_show_Screenshot_2021-05-12_10-10-23](https://user-images.githubusercontent.com/55546823/117941643-9bced380-b30a-11eb-925a-07d295dd815e.png)

strange is, that the "direct" ACK send from the end-device to the servers message (3) is recognized and handled:

coap          | send OAD/NTF to  fdde:ad00:beef:0:c61c:db97:a036:c51a
coap          | ACK received from fdde:ad00:beef:0:c61c:db97:a036:c51a ACK:

**Comment by jkralik** [comment]
@slaesh could you show me a code how you POST `oad/ntf` ? because it seems that the device uses same connection (port 52705) to get "oad/img" but `udpListener` listens on 5683 port.

**Comment by slaesh** [comment]
oh, good eyes! didn't noticed that..

```golang
// Post ...
func Post(ip config.IPv6, topic string, payload []byte, retryCnt int) {
	co, err := udp.Dial("["+string(ip)+"]:5683", udp.WithErrors(func(err error) {
		// fmt.Println("here we are..", err)
	}))
	if err != nil {
		log.Printf("Error dialing: %v", err)
	}
	defer co.Close()

	// create context with timeout
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond*500)
	defer cancel()

	// send our post
	resp, err := co.Post(ctx, topic, message.AppOctets, bytes.NewReader(payload))
	if err != nil {
		fmt.Println("coap-post: error sending post", err, ip)

		if retryCnt > 0 {
			fmt.Println("retry!", retryCnt)
			Post(ip, topic, payload, retryCnt-1)
		}

		return
	}

	// read "data" from the ACK response
	if resp.Type() == udpMessage.Acknowledgement {
		data, _ := ioutil.ReadAll(resp.Body())

		msg := fmt.Sprintf("%s ACK received from %v ACK: %s",
			time.Now().Format("[15:04:05.000]"), ip, string(data),
		)
		fmt.Println(msg)
	}

	// do we need to send an ACK?
	if resp.Type() == udpMessage.Confirmable {
		fmt.Println("send ACK")

		resp.Message.Reset()                     // dont sent content again
		resp.SetType(udpMessage.Acknowledgement) // its an ACK..

		err = co.WriteMessage(resp)
		if err != nil {
			fmt.Println("something went wrong..")
		}
	}

	// fmt.Println("post done!")
}
```

**Comment by slaesh** [comment]
c++ "oad/ntf" message:

![image](https://user-images.githubusercontent.com/55546823/117976949-9b493380-b330-11eb-9fd5-a3942997d10e.png)

using 5683 for src and dst ..

my golang "oad/ntf" message:

![image](https://user-images.githubusercontent.com/55546823/117978303-047d7680-b332-11eb-9a28-32cfee1f776e.png)

NOTE: ip addresses changed..

but, why are "we" using different ports?
and how can I "change" the token? :)

**Comment by jkralik** [comment]
So at your code I see `defer co.Close()` this is why the port is not accessible.

Why you don't use `ClientConn()` https://github.com/plgd-dev/go-coap/blob/master/mux/client.go#L22. from ResponseWriter ?
eg:
```
func myhandler(w ResponseWriter, r *Message) {
       co := w.ClientConn().(*udp.ClientConn)

       // create context with timeout
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond*500)
	defer cancel()

	// send our post
	resp, err := co.Post(ctx, topic, message.AppOctets, bytes.NewReader(payload))
	if err != nil {
		fmt.Println("coap-post: error sending post", err, ip)

		if retryCnt > 0 {
			fmt.Println("retry!", retryCnt)
			Post(ip, topic, payload, retryCnt-1)
		}

		return
	}

	// read "data" from the ACK response
	if resp.Type() == udpMessage.Acknowledgement {
		data, _ := ioutil.ReadAll(resp.Body())

		msg := fmt.Sprintf("%s ACK received from %v ACK: %s",
			time.Now().Format("[15:04:05.000]"), ip, string(data),
		)
		fmt.Println(msg)
	}

	// do we need to send an ACK?
	if resp.Type() == udpMessage.Confirmable {
		fmt.Println("send ACK")

		resp.Message.Reset()                     // dont sent content again
		resp.SetType(udpMessage.Acknowledgement) // its an ACK..

		err = co.WriteMessage(resp)
		if err != nil {
			fmt.Println("something went wrong..")
		}
	}
}
```

**Comment by jkralik** [comment]
> but, why are "we" using different ports?

In your code you call dial:
```
co, err := udp.Dial("["+string(ip)+"]:5683", udp.WithErrors(func(err error) {
		// fmt.Println("here we are..", err)
	}))
```

> and how can I "change" the token? :)

`co.Post` generates token self so you need to call 
```
req, err := client.NewPostRequest()`
if err != nil {
  ...
}
req.SetToken([]byte("myToken"))
resp, err := co.Do(ctx, req)
...
```

**Comment by slaesh** [comment]
Thanks! You meant `w.Client().ClientConn()`, right? =)

That "Post" function is used in general, not only in middleware-context's..
Maybe I need to have two separate functions.. Used from somewhere and used within the middleware stuff :thinking: ?

Thanks for the hints, will test some further!! :+1:

**Comment by slaesh** [comment]
okay, I see the problem now.. One question @jkralik is still remaining..

I set `withKeepAlive`to nil, to NOT let the connection being active.. Since I have several "sleepy" devices, which will not be online all the time..
So.. How do I know if there is already a connection "established" to the device I want to talk to right now..

Do I need to "remind" me the latest `ClientConn`? And how to check if its still active?
As long as I am acting inside my middleware, everything is fine..

But what happens if I am acting with the device from "another context" .. Without the awareness of `w ResponseWriter` .. :)
There is this `udp.WithOnNewClientConn` .. Which I could use.. but still not sure how to determine if its closed or not =)

Hope you can follow me.. :P

**Comment by slaesh** [comment]
or do I have to close the connection by myself after calling `SetResponse` .. to be sure its closed? :thinking:

**Comment by jkralik** [comment]
WithKeepAlive(nil) - it means that you need to care about close connection. You can check if it is still alive with some request to the device. Some users uses `WithInactivityMonitor` which automatically "Close" the session when there is inactivty for while, which can solve the issue. eg https://github.com/plgd-dev/go-coap/blob/7c589011f8bd90f9ee4e0dc86aca4d74256abaab/udp/server_test.go#L178

For UDP server client.Close just free session from memory - it doesn't close connection because it is shared among sessions.
