### ISSUE TITLE
DTLS Server and Client role: should it work?

### ISSUE THREAD

**Issue by emillindq** [plgd-dev/go-coap#231]
Hi!

I am wondering if go-coap is designed to have both server and client role in a DTLS connection. I have go-coap setup as a DTLS server and CoAP server, and then I want to use the established DTLS connection to do client requests to the remote device.

I have seen that I can gain access to the `client.ClientConn` if I register a callback using `WithOnNewClientConn` option when calling `dtls.NewServer`. I can then call cc.Get() to do my requests as a client to the remote device.

My scenario is that the remote device downloads firmware using blockwise transfer (aka. lots of GET requests), and then I simultaneously poll the remote device using a GET request from my end (as a client role). It works, most of the time, but sometimes I get timeout from the client GET request even though I can see in Wireshark that the remote device answers. Furthermore, from that point on I can also see that the go-coap server intermittently sends out two datagram replies to one GET request from the remote device, but where one is a very old block number. It's also always the same block number that is sent out extra.

I have 10 seconds timeout on the client in go-coap, and the client runs in its own goroutine.

I guess my question is if this is a bug, if I'm doing it wrong, or if it's not supposed to work in the first place.

Thanks!

**Comment by jkralik** [comment]
Hi @emillindq.
At first I know about one issue and it is in blockwise. Current go-coap allows you to create multiple blockwise transfers to the same resource but this is forbidden by RFC https://datatracker.ietf.org/doc/html/rfc7959#section-2.4 , https://datatracker.ietf.org/doc/html/rfc7959#section-2.5 - the last sections. So maybe this why it sometime fails. So at your client you need to guaranteed that only one GET/POST to the one resource(same href) is processed in same time.

**Comment by emillindq** [comment]
> Hi @emillindq.
> At first I know about one issue and it is in blockwise. Current go-coap allows you to create multiple blockwise transfers to the same resource but this is forbidden by RFC https://datatracker.ietf.org/doc/html/rfc7959#section-2.4 , https://datatracker.ietf.org/doc/html/rfc7959#section-2.5 - the last sections. So maybe this why it sometime fails. So at your client you need to guaranteed that only one GET/POST to the one resource(same href) is processed in same time.

Thanks for your reply! I am 99% sure this is not the case; the only one doing blockwise transfer is my remote client when it is downloading firmware and it's basically impossible for that task to become duplicate. It looks well-behaved according to Wireshark in that respect.

What I'm curious about is if go-coap is even designed to have both server & client CoAP roles over a pion DTLS connection? I could imagine it would work unintentionally but then I'd run into problems with mutual exclusion and such if it wasn't designed for it since my client is running in a different goroutine.

Thanks!
