### ISSUE TITLE
How can a dtls server accept a client re-sending dtls handshake request?

### ISSUE THREAD

**Issue by rtechencheng** [plgd-dev/go-coap#245]
Hi,
I use your examples/dtls/psk/server implementation. But I have a different client client which uses [tinydtls](https://github.com/contiki-ng/tinydtls).

When the server is reset and clients also reset, the client connect to server successfully and handshake has no problem.
Then if I reset the client from the connected state, e.g. power cycle the device (the reset will take more than 1 minute), the client will send client_hello again. But the server will never respond to that. (Basically no logs...)

I have tried both:
```
	log.Fatal(coap.ListenAndServeDTLS("udp", ":5688", &piondtls.Config{
		PSK: func(hint []byte) ([]byte, error) {
			fmt.Printf("Client's hint: %s \n", hint)
			if dtlsIdentity != string(hint) {
				// Falsify the handshake
				return []byte{}, nil
			}
			return dtlsPskByteArray, nil
		},
		// Don't provide any PSKIdentityHint
		CipherSuites: []piondtls.CipherSuiteID{piondtls.TLS_PSK_WITH_AES_128_CCM_8},
		ConnectContextMaker: func() (context.Context, func()) {
			return context.WithTimeout(context.Background(), 10*time.Second)
		},
	}, m))
```
and
```
	log.Fatal(coap.ListenAndServeDTLS("udp", ":5688", &piondtls.Config{
		PSK: func(hint []byte) ([]byte, error) {
			fmt.Printf("Client's hint: %s \n", hint)
			if dtlsIdentity != string(hint) {
				// Falsify the handshake
				return []byte{}, nil
			}
			return dtlsPskByteArray, nil
		},
		// Don't provide any PSKIdentityHint
		CipherSuites: []piondtls.CipherSuiteID{piondtls.TLS_PSK_WITH_AES_128_CCM_8},
	}, m))
```
None of them works.
Detailed DTLS config setup is derived from here:
https://github.com/pion/dtls/issues/389

Could anyone kindly help me on this?
Thanks!

**Comment by rtechencheng** [comment]
I guess the problem I have is that once the server creates a client connection, it never drops it. But if the client just crash and resend any request, the server will not "hear" anything since there is already a running connection.

**Comment by jkralik** [comment]
Hi.
Yes you can set up an inactivity monitor: via `WithInactivityMonitor()` server option  - similar as in test: https://github.com/plgd-dev/go-coap/blob/master/dtls/server_test.go#L165

**Comment by rtechencheng** [comment]
Hi,
Thanks for your reply. I have tried overriding your `ListenAndServeDTLS` function:
```
// ListenAndServeDTLS Starts a server on address and network over DTLS specified Invoke handler
// for incoming queries.
func ListenAndServeDTLS(network string, addr string, config *piondtls.Config, handler mux.Handler) error {
	l, err := net.NewDTLSListener(network, addr, config)
	if err != nil {
		return err
	}
	defer l.Close()
	// s := dtls.NewServer(dtls.WithMux(handler))
	var checkCloseWg sync.WaitGroup
	defer checkCloseWg.Wait()
	s := dtls.NewServer(
		dtls.WithMux(handler),
		dtls.WithOnNewClientConn(func(cc *client.ClientConn, tlscon *piondtls.Conn) {
			checkCloseWg.Add(1)
			cc.AddOnClose(func() {
				checkCloseWg.Done()
			})
		}),
		dtls.WithKeepAlive(3, 1*time.Hour, func(cc inactivity.ClientConn) {
			cc.Close()
		}),
	)
	return s.Serve(l)
}
```
However, when the client crashes and resend connection request, I still don't see the server responding to that. I guess the server does not treat that as a new client, or?

**Comment by rtechencheng** [comment]
Close this since I found the root cause is actually on `pion/dtls`:
https://github.com/pion/dtls/issues/253
