### ISSUE TITLE
Remove multiple cache-maps

### ISSUE THREAD

**Issue by jkralik** [plgd-dev/go-coap#248]
Currently, for each UDP/TCP connection, it creates 1-3 cache maps and each of them starts a goroutine that checks the expiration of items. We need to use only one cache which can be configured from outside of the package to improve performance.

Eg: 1000 connections -> means 1000-3000 executions per second.

**Comment by jkralik** [comment]
Hi @arun1587  What is your current state? Thx

**Comment by arun1587** [comment]
still in progress. didn't proceed much due to my vacation. should be able to push some stuff for UDP by the end of september. you could go ahead if its urgent from your side.
