### ISSUE TITLE
SetToken in SetResponse

### ISSUE THREAD

**Issue by arigon** [plgd-dev/go-coap#251]
Hi

I'm using SetResponse for responses to confirmable requests. Is it somehow possible to set the Token in SetResponse?
SetResponse is using the pool.Message which has SetToken available. So it should be easily possible to add SetToken into SetResponse but it would be a breaking change.

Alex

**Comment by jkralik** [comment]
Hi. The token is driven by go-coap. But what you can do is that you don't send a response via `SetResponse` but via WriteMessage where you can put your token. Something similar as is in https://github.com/plgd-dev/go-coap/blob/231b8cdcfcc3c892098539a987c14d7c415c0838/examples/observe/server/main.go#L78

**Comment by arigon** [comment]
I tried, but WriteMessage has no ACK.

**Comment by jkralik** [comment]
ACK is sent via in separate message. So you just send a CON message.

**Comment by arigon** [comment]
Can you please give an example?

**Comment by jkralik** [comment]
eg:

```golang
func sendResponse(cc mux.Client, token []byte) error {
       m := message.Message{
		Code:    codes.Content,
		Token:   token,
		Context: cc.Context(),
		Body:    bytes.NewReader([]byte("data")),
	}
	var opts message.Options
	var buf []byte
	opts, n, err := opts.SetContentFormat(buf, message.TextPlain)
	if err == message.ErrTooSmall {
		buf = append(buf, make([]byte, n)...)
		opts, n, err = opts.SetContentFormat(buf, message.TextPlain)
	}
	if err != nil {
		return fmt.Errorf("cannot set content format to response: %w", err)
	}
	m.Options = opts
	return cc.WriteMessage(&m)
}


mux.HandlerFunc(func(w mux.ResponseWriter, r *mux.Message) {
  // we send response in another goroutine - so the peer gets separate message
  go func() {
    time.Sleep(time.Second*10) // do something
    err := sendResponse(w.Client(), r.Token)
    if err != nil {
      log.Printf("Error on transmitter: %v", err)
    }
  }()
})
```

**Comment by arigon** [comment]
But where is the ACK?

**Comment by jkralik** [comment]
It is handled by go-coap via separate message.

Dňa ut 28. 9. 2021, 21:08 Alex ***@***.***> napísal(a):

**Comment by arigon** [comment]
Well it doesn't. I tried it these days (I used the WriteMessage from the example) and the client (a sensor) isn't receiving the ACK. It only works with SetResponse.

**Comment by jkralik** [comment]
In `v3` you can edit response message as you need it. 

https://github.com/plgd-dev/go-coap/blob/b8901963ae43acd9a14f98b3d47ec17b26b38e7a/net/responsewriter/responseWriter.go#L65

Feel free to reopen the issue.
