### ISSUE TITLE
Observe Resource behavior according to RFC 7641

### ISSUE THREAD

**Issue by TheDarkPyotr** [plgd-dev/go-coap#262]
Hi, 
I've read the [RFC 7641](https://datatracker.ietf.org/doc/html/rfc7641) (observing resources in CoAP) but i don't fully understand the behavior of the example in [examples/observe](https://github.com/plgd-dev/go-coap/tree/master/examples/observe). 
The server with func _periodicTransmitter_ send messages to clients every second but the clients only receive messages every two minutes inside the func _observeFunc_. How can I allow the client to read all (_or most_) of the messages sent by the server?
Thanks for your time

**Comment by jkralik** [comment]
Hi. Thx reporting the issue. There was implemented the deduplication of notification some time ago. And the server sends a notification without increasing the observation option.  So it is fixed in commit https://github.com/plgd-dev/go-coap/pull/263/commits/b60e8efc1e3ed4551d65b34a563147eb308dca3f

**Comment by TheDarkPyotr** [comment]
Thank you for the quick response!
