### ISSUE TITLE
Multicast and Unicast server on same port

### ISSUE THREAD

**Issue by HRogge** [plgd-dev/go-coap#271]
Is it possible for a server using this library to receive both unicast and multicast messages on the same UDP port?

**Comment by jkralik** [comment]
Hi. The multicast messages support only the server and yes you can use the same port. Pls look to example:

- create listen port:
https://github.com/plgd-dev/go-coap/blob/master/examples/mcast/client/main.go#L66
- create the server
https://github.com/plgd-dev/go-coap/blob/master/examples/mcast/client/main.go#L80

**Comment by HRogge** [comment]
Thank you for the quick answer, it made me notice that I got drawn to the old (v1?) codebase by an example on pkg.go.dev. I will now look at the new codebase...

**Comment by HRogge** [comment]
Is there also an example for sending a multicast message (udp message, non-confirmable, Option NoResponse-2) instead of a Discovery?
I got the message sending done, but the client waits for the response which the server doesn't send.

**Comment by HRogge** [comment]
solved by #291 and some explanations.
thank you for merging the code that quickly
