### ISSUE TITLE
not get block2 option in server

### ISSUE THREAD

**Issue by lx121451** [plgd-dev/go-coap#278]
When I  send a Get Message with block2 option，but in server side Options.HasOption(message.Block2) return false。Is there anything that needs special attention？

**Comment by Danielius1922** [comment]
@jkralik I think this is the relevant code:

https://github.com/plgd-dev/go-coap/blob/49cae1ca2883b97159e646b1d05635ceb1f21bd6/net/blockwise/blockwise.go#L534-L540

Do you recall why the `Block2` option is removed from the message before its passed to the `next` handler function?

**Comment by jkralik** [comment]
@lx121451 Pls, why do you need `block2`?  Thx

**Comment by jkralik** [comment]
> Do you recall why the `Block2` option is removed from the message before its passed to the `next` handler function? Maybe the error check is inverted?

No, it's correct.

**Comment by lx121451** [comment]
> @lx121451 Pls, why do you need `block2`? Thx

Just for test，I'm simulating a file transfer server with separate response！

**Comment by JosefWN** [comment]
> A CoAP message, appropriately encapsulated, SHOULD fit within a
   single IP packet (i.e., avoid IP fragmentation) and (by fitting into
   one UDP payload) obviously needs to fit within a single IP datagram.
   If the Path MTU is not known for a destination, an IP MTU of 1280
   bytes SHOULD be assumed; if nothing is known about the size of the
   headers, good upper bounds are 1152 bytes for the message size and
   1024 bytes for the payload size.

https://datatracker.ietf.org/doc/html/rfc7252

It's not common, but it's also not _uncommon_, that my response payload exceeds 1024 bytes and then some, in which case I assume I would need `block2` (or `block4`) transfers to fulfill the RFC 7252 recommendations?

The `README.md` also hints at `go-coap` being compliant with RFC 7959?
> Block-wise transfers in CoAP RFC 7959

**Comment by jkralik** [comment]
For test you can use https://github.com/plgd-dev/go-coap/blob/master/options/commonOptions.go#L278 to watch all messages that comes to server in `v3`.
I will close the issue, feel free to reopen it.
