### ISSUE TITLE
unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by georges-honore-figfi** [plgd-dev/go-coap#323]
I have an existing project. I tried to port it from v2.4.0 to 2.5.0. 
It compiles, but I get a runtime error "unaligned 64-bit atomic operation" when it runs. 
The program is compiled and run on an arm6.
[go1.18.1.linux-armv6l.tar.gz](https://go.dev/dl/go1.18.1.linux-armv6l.tar.gz)

**Comment by IHIDCHAOS** [comment]
Can this [Pull ](https://github.com/plgd-dev/go-coap/pull/305) solve your problem？

**Comment by georges-honore-figfi** [comment]
Thank you very much for your response.
Yes, this seems to have resolved the issue.

**Comment by Danielius1922** [comment]
Nice, thanks for reporting AND fixing!
