### ISSUE TITLE
Little endian ETag?

### ISSUE THREAD

**Issue by JosefWN** [plgd-dev/go-coap#345]
According to RFC7252:
> All multi-byte integers in this protocol are interpreted in network byte order.

... but it seems `GetETag` returns a little endian checksum, is this intentional?
https://github.com/plgd-dev/go-coap/blob/004711823039d45af60bce6c639835a180f78bdd/message/getETag.go#L42

**Comment by Danielius1922** [comment]
That seems really suspicious indeed. @jkralik: any reason why this is little endian while everything else is big endian?

**Comment by jkralik** [comment]
Yes this is a bug.

**Comment by Danielius1922** [comment]
Thanks for the catch @JosefWN !
