### ISSUE TITLE
Comment on SetObserve method is confusing

### ISSUE THREAD

**Issue by tim-golioth** [plgd-dev/go-coap#384]
I can submit a PR for this, but I wanted to check first that I'm not reading the code incorrectly.

The comment for the [SetObserve](https://github.com/plgd-dev/go-coap/blob/948a0bcf18a66f92d7269f40104a64e997498d3b/message/options.go#L338) method reads:

```
// SetObserve sets ContentFormat option.
func (options Options) SetObserve(buf []byte, observe uint32) (Options, int, error) {
...
```

That should be `SetObserve sets the Observe option.` Correct?

**Comment by Danielius1922** [comment]
Yes, must have been a copy & paste error on my part.
