### ISSUE TITLE
how do i do the tls / letsencrypt equivalent of a secure connection?

### ISSUE THREAD

**Issue by ultperf** [plgd-dev/go-coap#408]
1. any example for the tls secure end to end encryption using the "NOISE" type?
2. is there a websocket example of this coap?

**Comment by jkralik** [comment]
Hi @ultperf 

> 1. any example for the tls secure end to end encryption using the "NOISE" type?

This question belongs to another packages which are used by go-coap: https://github.com/pion/dtls or https://github.com/golang/go part crypto/tls - but I think they don't support the NOISE feature.

> 2. is there a websocket example of this coap?

coap  has observation [RFC7641](https://www.rfc-editor.org/rfc/rfc7641) - client/server example you can find at:
https://github.com/plgd-dev/go-coap/tree/master/examples/observe
