### ISSUE TITLE
Bidirectional examples missing

### ISSUE THREAD

**Issue by ehmry** [plgd-dev/go-coap#429]
CoAP and CoAP+TCP both support bidirectional requests. I'm confident that go-coap supports this but it isn't clear what a reasonably straightforward way do to this would be.

I need to figure out how this is done and if I find good way I may make a PR.

**Comment by jkralik** [comment]
Yes it is supported. We are using it in our coap-gateway (OCF reference implementation): https://github.com/plgd-dev/hub/tree/main/coap-gateway/service

eg:
- update resource: https://github.com/plgd-dev/hub/blob/133c1b28583059510e170bf6e7e64b0a4d35baf6/coap-gateway/service/session.go#L564
- retrieve resource: https://github.com/plgd-dev/hub/blob/133c1b28583059510e170bf6e7e64b0a4d35baf6/coap-gateway/service/session.go#L632
...

**Comment by ehmry** [comment]
Yes, this what I was looking for, thank you.
