### ISSUE TITLE
Move from `pion/udp` to `pion/transport`

### ISSUE THREAD

**Issue by hasheddan** [plgd-dev/go-coap#447]
https://github.com/pion/udp has been deprecated in favor of https://github.com/pion/transport/tree/master/udp, and recommends updating dependencies.

I'd be happy to work on this! 🙂

**Comment by Danielius1922** [comment]
Hello there, fellow Daniel.

The interface looks the same, in fact it just may be the same code moved to a different repo. Go for it!

**Comment by hasheddan** [comment]
Hey folks! Yep I believe it is the same :)

Opened https://github.com/plgd-dev/go-coap/pull/448 to update!
