### ISSUE TITLE
Media type strings do not match IANA registry

### ISSUE THREAD

**Issue by hasheddan** [plgd-dev/go-coap#492]
Similar to #484, many of the [media types](https://github.com/plgd-dev/go-coap/blob/24bc8fe40ed44e700eaec7bd8969cfc0f102a96f/message/option.go#L193) do not match their representation in the [IANA registry](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats), which can make it difficult to handle them generically. Most of the offenders are due to the inclusion of the RFC suffix.

**Comment by hasheddan** [comment]
Happy to make the necessary updates here, @jkralik are you open to moving towards matching the IANA registry?

**Comment by hasheddan** [comment]
@Danielius1922 I am happy to work on this if you want to assign me 🙂

**Comment by Danielius1922** [comment]
Sounds alright to me, I've checked our repositories and the only place we use it is in a test. But there might be some hidden code I don't have access to, so we must wait for @jkralik to say if it is alright.

**Comment by Danielius1922** [comment]
@hasheddan I've talked with @jkralik about this, and we think can remove the RFC suffixes.

**Comment by hasheddan** [comment]
@Danielius1922 thanks! Will do shortly 👍🏻
