### ISSUE TITLE
ListenAndServeWithOptions doesn't correctly start UDP server

### ISSUE THREAD

**Issue by sdeboeck** [plgd-dev/go-coap#526]
The ListenAndServeWithOptions function does not correctly start the UDP server when using udpServer.Option. 
The UDP options are not being populated, leading to unexpected behavior.

**Steps to Reproduce**

1. Use the ListenAndServeWithOptions function to start a CoAP server with UDP
2. Provide options.WithMux option.
3. The server doesn't invoke the desired handlers.

https://github.com/plgd-dev/go-coap/blob/c61c6485126a661ad05a5b49080ed604e7ad3cc3/server.go#L87

**Comment by Danielius1922** [comment]
Fixed by the linked PR.
