### ISSUE TITLE
Example Server UDP: sendmsg: invalid argument

### ISSUE THREAD

**Issue by timonaldenhoff** [plgd-dev/go-coap#577]
Go Version: `1.22.6´

When running the example [server](https://github.com/plgd-dev/go-coap/blob/master/examples/simple/server/main.go) and [client](https://github.com/plgd-dev/go-coap/blob/master/examples/simple/client/main.go), the server is not able to write a respone:

```
2024/08/31 18:12:04 ClientAddress 127.0.0.1:64706, Code: GET, Token: 63e8227ae393a9f2, Path: /b, Type: Confirmable, MessageID: 40391
2024/08/31 18:12:04 cannot set response: cannot write request: write udp [::]:5688->127.0.0.1:64706: sendmsg: invalid argument
udp: cannot write response: cannot write request: write udp [::]:5688->127.0.0.1:64706: sendmsg: invalid argument
2024/08/31 18:12:08 ClientAddress 127.0.0.1:64706, Code: GET, Token: 63e8227ae393a9f2, Path: /b, Type: Confirmable, MessageID: 40391
2024/08/31 18:12:08 cannot set response: cannot write request: write udp [::]:5688->127.0.0.1:64706: sendmsg: invalid argument
udp: cannot write response: cannot write request: write udp [::]:5688->127.0.0.1:64706: sendmsg: invalid argument
```

When I am switching to tcp it works: `coap.ListenAndServe("udp", ":5688", r)` -> `coap.ListenAndServe("tcp", ":5688", r)` 

Or when I am using my localhost: `coap.ListenAndServe("udp", "127.0.0.1:5688", r)`

I am not sure, if it is a firewall issue from my side, but I have tested it also on my server (where the same config with the package `"github.com/go-ocf/go-coap"` was running).

Do you have any ideas?

**Comment by jkralik** [comment]
Hi @timonaldenhoff 

The issue is that sending messages from IPv6 to IPv4 is not supported. Therefore, you need to use either coap.ListenAndServe("udp4", ":5688", r) for IPv4 or coap.ListenAndServe("udp6", ":5688", r) for IPv6. On Linux systems, both IPv4 and IPv6 addresses may be listened to, but this is not guaranteed.

**Comment by timonaldenhoff** [comment]
Thank you very much @jkralik, this fixed my issue!
