### ISSUE TITLE
sendmsg invalid argument on udp connections with go-coap version >= 3.2.0

### ISSUE THREAD

**Issue by kgoguevvoi** [plgd-dev/go-coap#581]
When attempting to upgrade our server which relies on go-coap v2 to v3 (latest) we encountered an issue with udp connections not being able to be written to from the server.  As an attempt to check if the latest code is working we resorted to using the simple coap example bundled with the repository.  When running the server and the client we are met with `sendmsg: invalid argument` on versions >= 3.2.0

The issue is not present on tag v3.1.6. However this presents issues for anyone that wants to use the latest version of the go-coap library.

The issue has been tested on the following platforms
```
* Linux 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
* Linux 6.10.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 10 Sep 2024 14:37:32 +0000 x86_64 GNU/Linux
```

How to reproduce: 
1. Checkout the tag 3.2.0 and run the simple example server then client
2. Server fails to respond to client with invalid argument 
```
2024/09/16 15:31:27 ClientAddress 127.0.0.1:52765, Code: GET, Token: 0ab50dc5d0fdc417, Path: /a, Type: Confirmable, MessageID: 45080
udp: cannot write response: cannot write request: write udp [::]:5688->127.0.0.1:52765: sendmsg: invalid argument
2024/09/16 15:31:28 Error sending request: cannot write request: cannot write request: context deadline exceeded
exit status 1

```
3.  Checkout the tag 3.1.6 and run the simple example server then client
4.  Server responds as expected:
```
2024/09/16 15:36:41 ClientAddress 127.0.0.1:52530, Code: GET, Token: f29a0fd787cdc463, Path: /a, Type: Confirmable, MessageID: 53194
2024/09/16 15:36:41 Response payload: Code: Content, Token: f29a0fd787cdc463, ContentFormat: text/plain; charset=utf-8, Type: Acknowledgement, MessageID: 53194, PayloadLen: 11
```

Expected:
No error on server side with go-coap versions > 3.1.6

**Comment by jlevesy** [comment]
From our investigation, It appears that this comes from https://github.com/plgd-dev/go-coap/pull/510.
Commenting out https://github.com/plgd-dev/go-coap/pull/510/files#diff-a402fa7bd40fa4f6ed3f7ae900a58d45e2f4b4ee9ba56f44c75fd8ac4d97d1e2R734  and https://github.com/plgd-dev/go-coap/pull/510/files#diff-a402fa7bd40fa4f6ed3f7ae900a58d45e2f4b4ee9ba56f44c75fd8ac4d97d1e2R766 makes the server works again in our case.

**Comment by jkralik** [comment]
Hi @jlevesy and @kgoguevvoi. Pls could you test if https://github.com/plgd-dev/go-coap/pull/582 fixes the issue ?

**Comment by jlevesy** [comment]
Just tried it. It does work! Thanks a lot for the quick fix!
